spring.application.name=TourplannerBackend

spring.datasource.url=jdbc:postgresql://localhost:5432/tourplannerdb
spring.datasource.username=swen2user
spring.datasource.password=swen2pw

jwt.secret=XAH8uxu1CTXt/QP4PWp/oQxUHZLEx5/VwcyZIclS4Ac=
openrouteservice.api-key=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjNkZjVjYzVhMDc4MjRlZjViOWNmOTAwYzIwZTBhZDc3IiwiaCI6Im11cm11cjY0In0=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

